# Servicios de la aplicación
services:
  # Servicio de la API REST
  shop-api-rest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop-api-rest
    restart: always
    env_file: .env
    ports:
      - ${API_PORT}:3000
    volumes:
      - storage-dir:/app/storage-dir
    networks:
      - shop-network

# Volume para guardar los datos de la base de datos
volumes:
  storage-dir:

networks:
  shop-network:
    driver: bridge